POST http://localhost:7071/api/PostJournalEntry HTTP/1.1
content-type: application/json

{
    "name": "sample",
    "date": "Wed, 21 Oct 2015 18:27:50 GMT"
}

###
POST http://localhost:7071/api/PostJournalEntry HTTP/1.1
content-type: application/json

{
    "name": "Gone With The Wind",
    "author": "Margaret Mitchell",
    "date": "Wed, 21 Oct 2015 18:27:50 GMT"
}